version: 0.2.0.{build}
os: Visual Studio 2017
install:
  - if not exist dotnet-dev-win-x64.latest.zip appveyor DownloadFile https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-dev-win-x64.latest.zip -FileName "dotnet-dev-win-x64.latest.zip"  
  - cmd: 7z x dotnet-dev-win-x64.latest.zip -oc:\dotnet

before_build:
- cmd: git submodule update --init --recursive
- cmd: path c:\dotnet
- cmd: dotnet --info  

build_script:
- cmd: dotnet --info
- ps: path c:\dotnet
- ps: $url1='https://img.shields.io/badge/version-v0.2.' + $env:APPVEYOR_BUILD_NUMBER  + '-blue.svg'
- ps: .\download.ps1 $url1 "latest-version-badge.svg"
- ps: .\build.ps1

test: off

artifacts:
- path: artifacts/zip/*.zip
- path: latest-version-badge.svg